export enum BoundNodes {
  BoundProgramNode = "BoundProgramNode",
  BoundIntegerLiteral = "BoundIntegerLiteral",
  BoundFloatLiteral = "BoundFloatLiteral",
  BoundStringLiteral = "BoundStringLiteral",
  BoundBooleanLiteral = "BoundBooleanLiteral",
  BoundNilLiteral = "BoundNilLiteral",
  BoundObjectProperty = "BoundObjectProperty",
  BoundObjectLiteral = "BoundObjectLiteral",
  BoundIdentifier = "BoundIdentifier",
  BoundMemberExpression = "BoundMemberExpression",
  BoundParenthesizedExpression = "BoundParenthesizedExpression",
  BoundLambdaExpression = "BoundLambdaExpression",
  BoundParameter = "BoundParameter",
  BoundCallExpression = "BoundCallExpression",
  BoundBinaryOp = "BoundBinaryOp",
  BoundAssignmentExpression = "BoundAssignmentExpression",
  BoundVariableDeclaration = "BoundVariableDeclaration",
  BoundFunctionDeclaration = "BoundFunctionDeclaration",
  BoundReturnStatement = "BoundReturnStatement",
  BoundBlock = "BoundBlock",
  BoundLogicalOperation = "BoundLogicalOperation",
}
