export enum TokenNames {
  Integer = "Integer",
  Float = "Float",
  String = "String",
  True = "True",
  False = "False",
  Nil = "Nil",
  NaN = "NaN",
  Infinity = "Infinity",
  Plus = "Plus",
  Minus = "Minus",
  Times = "Times",
  Div = "Div",
  Mod = "Mod",
  LBracket = "LBracket",
  RBracket = "RBracket",
  Colon = "Colon",
  Dot = "Dot",
  Equals = "Equals",
  EOF = "EOF",
}
