export enum TokenNames {
  Integer = "Integer",
  Float = "Float",
  String = "String",
  True = "True",
  False = "False",
  Nil = "Nil",
  NaN = "NaN",
  Infinity = "Infinity",
  Identifier = "Identifier",
  Plus = "Plus",
  Minus = "Minus",
  Times = "Times",
  Div = "Div",
  Mod = "Mod",
  LParen = "LParen",
  RParen = "RParen",
  LBrace = "LBracket",
  RBrace = "RBracket",
  Colon = "Colon",
  Dot = "Dot",
  Equals = "Equals",
  As = "As",
  EOF = "EOF",
}
