export enum SyntaxNodes {
  ProgramNode = "ProgramNode",
  IntegerLiteral = "IntegerLiteral",
  FloatLiteral = "FloatLiteral",
  StringLiteral = "StringLiteral",
  BooleanLiteral = "BooleanLiteral",
  NilLiteral = "NilLiteral",
  Identifier = "Identifier",
  ParenthesizedExpression = "ParenthesizedExpression",
  ObjectLiteral = "ObjectLiteral",
  ObjectProperty = "ObjectProperty",
  MemberExpression = "MemberExpression",
  AsExpression = "AsExpression",
  TypeAnnotation = "TypeAnnotation",
  IntegerKeyword = "IntegerKeyword",
  FloatKeyword = "FloatKeyword",
  BooleanKeyword = "BooleanKeyword",
  StringKeyword = "StringKeyword",
  TypeLiteral = "TypeLiteral",
}
